version: '3'

services:
  mongo-rs0-1:
    image: 'mongo-start-rs0'
    build: ./mongo-rs0-1
    ports:
      - '5001:27017' # left is computer's port right side is docker internal port
    volumes:
      - ./mongo-rs0-1/data:/data/db
    depends_on:
      - 'mongo-rs0-2'
      - 'mongo-rs0-3'

  mongo-rs0-2:
    image: 'mongo'
    command: --replSet rs0
    command: --config ./conf/mongo.conf
    ports:
      - '5002:27018'
    volumes:
      - ./mongo-rs0-2/data:/data/db
      - ./mongo-rs0-2/conf:/conf

  mongo-rs0-3:
    image: 'mongo'
    command: --replSet rs0
    command: --config ./conf/mongo.conf
    ports:
      - '5003:27019'
    volumes:
      - ./mongo-rs0-3/data:/data/db
      - ./mongo-rs0-3/conf:/conf

  mongo-rs1-1:
    image: 'mongo-start-rs1'
    build: ./mongo-rs1-1
    ports:
      - '6001:27017' # left is computer's port right side is docker internal port
    volumes:
      - ./mongo-rs1-1/data:/data/db
    depends_on:
      - 'mongo-rs1-2'
      - 'mongo-rs1-3'

  mongo-rs1-2:
    image: 'mongo'
    command: --replSet rs1
    command: --config ./conf/mongo.conf
    ports:
      - '6002:27018'
    volumes:
      - ./mongo-rs1-2/data:/data/db
      - ./mongo-rs1-2/conf:/conf

  mongo-rs1-3:
    image: 'mongo'
    command: --replSet rs1
    command: --config ./conf/mongo.conf
    ports:
      - '6003:27019'
    volumes:
      - ./mongo-rs1-3/data:/data/db
      - ./mongo-rs1-3/conf:/conf

  mongo-rsc-1:
    image: 'mongo-start-rsc'
    build: ./mongo-rsc-1
    ports:
      - '7001:27017' # left is computer's port right side is docker internal port
    volumes:
      - ./mongo-rsc-1/data:/data/db
    depends_on:
      - 'mongo-rsc-2'
      - 'mongo-rsc-3'

  mongo-rsc-2:
    image: 'mongo'
    command: --replSet rsc
    command: --config ./conf/mongo.conf
    ports:
      - '7002:27018'
    volumes:
      - ./mongo-rsc-2/data:/data/db
      - ./mongo-rsc-2/conf:/conf

  mongo-rsc-3:
    image: 'mongo'
    command: --replSet rsc
    command: --config ./conf/mongo.conf
    ports:
      - '7003:27019'
    volumes:
      - ./mongo-rsc-3/data:/data/db
      - ./mongo-rsc-3/conf:/conf

  setup-rs:
    image: 'setup-rs'
    build: ./setup
    depends_on:
      - 'mongo-rs0-1'
      - 'mongo-rs1-1'
      - 'mongo-rsc-1'

  # adminmongo:
  #   image: 'mrvautin/adminmongo'
  #   ports:
  #     - '1234:1234'
